#!/usr/bin/env bash
# Install nginx server and make / url return Hello World

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo "Hello World!" | tee /var/www/html/index.html

new_string="server_name _;\n\n        location / {\n                try_files /index.html =404;\n        }"
sudo sed -i "s#server_name _;#$new_string#" /etc/nginx/sites-enabled/default

sudo service nginx reload
