#!/usr/bin/env bash
# Install nginx server and add content to index.html

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
echo 'Hello World!' | tee /var/www/html/index.nginx-debian.html
