#!/usr/bin/env bash
# Install nginx server and make / url return Hello World and configure a 301 redirect

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo chmod -R 755 /etc/nginx/sites-enabled

new_string="server_name _;\n\n        location / {\n                try_files /index.html =404;\n        }"
sudo sed -i "s#server_name _;#$new_string#" /etc/nginx/sites-enabled/default

new_string="server_name _;\n\n        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s#server_name _;#$new_string#" /etc/nginx/sites-enabled/default

sudo service nginx reload
