#!/usr/bin/env bash
# Install nginx server and add content to index.html

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'

sudo service nginx start

echo 'Hello World!' > /var/www/html/index.html

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location / {
                try_files $uri $uri/ =404;
        }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart
