#!/usr/bin/env bash
# Install nginx server and add content to index.html, 404.html

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.html
sudo echo -e "Ceci n'est pas une page\n" | tee /var/www/html/404.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo chmod -R 755 /etc/nginx/sites-enabled

new_string="server_name _;\n\n        error_page 404 /404.html;\n        location /404.html {\n                root /var/www/html;\n        }"
sudo sed -i "s#server_name _;#$new_string#" /etc/nginx/sites-enabled/default

new_string="server_name _;\n\n        location /redirect_me {\n                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n        }"
sudo sed -i "s#server_name _;#$new_string#" /etc/nginx/sites-enabled/default

new_string="server_name _;\n\n        location / {\n                try_files /index.html =404;\n        }"
sudo sed -i "s#server_name _;#$new_string#" /etc/nginx/sites-enabled/default

sudo service nginx reload
