#!/usr/bin/env bash
# script to create mysql backup file and compress file to tar file

tar_file="$(date +'%d-%m-%Y').tar.gz"
mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$tar_file" backup.sql
