#!/usr/bin/env bash
# a script that runs infinitly and traps SIGTERM and SIGQUIT
file="/var/run/myscript.pid"
pid="$$"
echo "$pid" > $file

sigtermHandler() {
    echo "I hate the kill command"
    rm "$file"
    exit
}

trap sigtermHander SIGTERM SIGQUIT
trap "echo Y U no love me?!" SIGINT

while true
do
  echo "To infinity and beyond"
  sleep 2
done;
