#!/usr/bin/env bash
# this is a script that prints numbers, FIZZ, BUZZ and FIZZBUZZ
i=1
while [[ "$i" -le 100 ]]
do
    if [[ $((i % 3)) -eq 0 ]] && [[ $((i % 5)) -eq 0 ]]
    then
        echo "FizzBuzz"
    elif [[ $((i % 3)) -eq 0 ]]
    then
        echo "Fizz"
    elif [[ $((i % 5)) -eq 0 ]]
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    (( i++))
done
