#!/usr/bin/env bash
# printing numbers from 1 to 20 using while and case
count=1
while [[ "$count" -le 20 ]]
do
    echo "$count"
    case $count in
        4)
            echo "bad luck from China"
        ;;
        8)
            echo "bad luck from Japan"
        ;;
        17)
            echo "bad luck from Italy"
        ;;
        *)
        ;;
    esac
    (( count++ ))
done
