#!/usr/bin/env bash
# printing numbers from 1 to 20 using while
count=1
while [[ "$count" -le 20 ]]
do
    echo "$count"
    if [[ "$count" -eq 4 ]]
    then
        echo "bad luck from China"
    elif [[ "$count" -eq 8 ]]
    then
        echo "bad luck from Japan"
    elif [[ "$count" -eq 17 ]]
    then
        echo "bad luck from Italy"
    fi
    (( count++ ))
done
