#!/usr/bin/env bash
# printing numbers from 1 to 20 using while and case
hours=0
minutes=0
while [[ "$hours" -lt 12 ]]
do
    echo "Hour: $hours"
    while [[ "$minutes" -lt 60 ]]
    do
        echo "$minutes"
        (( minutes++ ))
    done
    (( hours++ ))
    minutes=0
done
