#!/usr/bin/env bash
# printing numbers from 1 to 20 using while and case
hours=0
minutes=1
while [[ "$hours" -le 12 ]]
do
    echo "Hour: $hours"
    while [[ "$minutes" -lt 60 ]]
    do
        echo "$minutes"
        (( minutes++ ))
    done
    (( hours++ ))
    minutes=1
done
