#!/usr/bin/env bash
# Install nginx server and configure it to return custom response header
# shellcheck disable=SC2154

HOSTNAME=$(hostname)

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
sudo echo 'Hello World!' | tee /var/www/html/index.html
sudo echo -e "Ceci n'est pas une page\n" | tee /var/www/html/404.html

sudo chown -R "$USER":"$USER" /etc/nginx/sites-enabled
sudo chmod -R 755 /etc/nginx/sites-enabled
sudo echo "
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location /redirect_me {
                add_header X-Served-By \$HOSTNAME;
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        location / {
                add_header X-Served-By \$HOSTNAME;
                try_files \$uri \$uri/ =404;
        }

        error_page 404 /404.html;
        location = /404.html {
                add_header X-Served-By \$HOSTNAME;
                internal;
        }
}" | sudo tee /etc/nginx/sites-enabled/default

sudo service nginx restart
