#!/usr/bin/env bash
# script to make nginx run with Nginx user and on port 8080
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
su nginx -s /bin/bash -c 'service nginx restart'
